[package]
name = "selfie-cli"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "selfie"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
clap = { version = "4.5.31", features = ["derive"] }
clap_complete = { version = "4.5", features = ["unstable-dynamic"] }
etcetera = "0.11"
shellexpand = "3.1"
comfy-table = { version = "8.0.0", features = ["custom_styling"] }
console.workspace = true
dialoguer = { version = "0.12", features = ["fuzzy-select"] }
indicatif.workspace = true
futures.workspace = true
human-panic = "2"
selfie = { path = "../selfie/" }
serde.workspace = true
serde-saphyr.workspace = true
tokio = { workspace = true, features = ["rt-multi-thread", "signal"] }
tokio-util.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true

[dev-dependencies]
assert_cmd = "2.0"
uuid.workspace = true
mockall.workspace = true
predicates = "3.1"
selfie = { path = "../selfie/", features = ["with_mocks"] }
tempfile.workspace = true
test-common = { path = "../test-common/" }
tokio-test = "0.4"
