//! Port for syncing package specs and dotfiles over git.

use std::future::Future;
use std::path::PathBuf;

use thiserror::Error;

use crate::package::event::EventStream;

/// Errors from sync preparation operations.
#[derive(Debug, Error)]
pub enum SyncError {
    /// The package directory is not inside a git repository.
    #[error("not a git repository: {path}")]
    NotARepo { path: PathBuf },

    /// A git operation failed during preparation.
    #[error("{0}")]
    GitError(String),

    /// One or more changed package files failed validation.
    #[error("validation failed for {} {}", .failures.len(), if .failures.len() == 1 { "package" } else { "packages" })]
    ValidationFailed {
        /// Per-file validation failures with structured details.
        failures: Vec<PackageValidationFailure>,
    },

    /// The process reached root through `sudo`.
    ///
    /// Committing and pushing as root leaves root-owned objects, refs and index
    /// entries inside a repository the user owns, which the next ordinary `git`
    /// fails on. Deploy state written as root is replaced by the next successful
    /// run, because it comes from a user-owned temporary file; git objects are
    /// not, so this does not self-heal.
    #[error("{}. {}", .0.message(), .0.suggestion())]
    Privilege(crate::privilege::SudoRefusal),
}

/// A single package file that failed validation during sync push.
#[derive(Debug, Clone)]
pub struct PackageValidationFailure {
    /// Relative path to the package file (e.g., `packages/topgrade.yml`).
    pub path: String,
    /// Structured validation issues found in this file.
    pub issues: Vec<PackageValidationIssue>,
}

/// A single validation issue within a package file.
#[derive(Debug, Clone)]
pub struct PackageValidationIssue {
    /// Severity: `"ERROR"` or `"WARN"`.
    pub level: String,
    /// Issue category (e.g., `"ParseError"`, `"RequiredField"`).
    pub category: String,
    /// The YAML field path affected (e.g., `"environments.test-env.install"`).
    pub field: String,
    /// Human-readable description.
    pub message: String,
    /// Source location from parse errors (e.g., `"line 17 column 1"`), or `None`
    /// for logical validation errors that don't map to a specific location.
    pub location: Option<String>,
}

/// Options controlling how `sync push` behaves.
#[derive(Debug, Clone, Default)]
pub struct PushOptions {
    /// Create a single commit for all changes instead of per-package commits.
    pub batch: bool,
    /// Override the commit message (only meaningful with `batch = true`).
    pub message: Option<String>,
    /// Skip per-commit prompts — use generated messages as-is.
    pub auto_accept: bool,
    /// Include non-package files in a "housekeeping" commit.
    pub include_ungrouped: bool,
}

/// A proposed commit generated by [`SyncService::prepare_push`].
///
/// Each pending commit groups related files (typically belonging to one package)
/// with a generated conventional commit message. The caller can inspect, edit,
/// or skip individual commits before passing them to [`SyncService::execute_push`].
#[derive(Debug, Clone)]
pub struct PendingCommit {
    /// Package name, or `"housekeeping"` for ungrouped files.
    pub name: String,
    /// Generated conventional commit message.
    pub message: String,
    /// Files to stage for this commit (relative to repo root).
    pub files: Vec<PathBuf>,
}

/// Result of [`SyncService::prepare_push`].
///
/// Contains proposed commits for new changes, plus metadata about the
/// current branch state (e.g., how many commits are already ahead of the
/// remote). This allows callers to distinguish "nothing at all" from
/// "no new commits but existing commits need pushing."
#[derive(Debug, Clone)]
pub struct PrepareResult {
    /// Proposed commits for uncommitted changes.
    pub pending_commits: Vec<PendingCommit>,
    /// Number of local commits already ahead of the remote.
    /// When this is > 0 and `pending_commits` is empty, the caller should
    /// still call [`SyncService::execute_push`] to push existing commits.
    pub ahead: usize,
    /// Non-fatal warnings the caller should display (e.g., ungrouped files skipped).
    pub warnings: Vec<String>,
}

/// A commit confirmed by the caller, with a potentially edited message.
///
/// Created from a [`PendingCommit`] after the caller has had a chance to
/// review and optionally edit the message.
#[derive(Debug, Clone)]
pub struct ConfirmedCommit {
    /// Files to stage for this commit (relative to repo root).
    pub files: Vec<PathBuf>,
    /// Final commit message (may have been edited by the user).
    pub message: String,
}

/// Port for the sync workflow — status, push and pull — so the CLI and MCP
/// server can drive it without knowing about git.
///
/// Push is two-phase on purpose: [`prepare_push`](Self::prepare_push) returns
/// proposed commits without touching git state, and
/// [`execute_push`](Self::execute_push) performs them, so a caller can ask the
/// user to confirm in between.
#[cfg_attr(any(test, feature = "with_mocks"), mockall::automock)]
pub trait SyncService: Send + Sync {
    /// Get combined repo status and dotfile drift summary.
    ///
    /// Emits [`SyncRepoStatus`](crate::package::event::PackageEvent::SyncRepoStatus)
    /// and [`SyncDriftSummary`](crate::package::event::PackageEvent::SyncDriftSummary)
    /// events, then completes.
    fn status(&self) -> impl Future<Output = EventStream> + Send;

    /// Analyze uncommitted changes and generate per-package commit proposals.
    ///
    /// This is a **non-mutating query** — no git state is changed. Returns a
    /// [`PrepareResult`] containing proposed commits and branch state metadata.
    ///
    /// Errors are returned directly (not as events) because this is a preparation
    /// step, not a long-running operation.
    fn prepare_push(
        &self,
        options: &PushOptions,
    ) -> impl Future<Output = Result<PrepareResult, SyncError>> + Send;

    /// Stage, commit, and push the confirmed commits.
    ///
    /// Emits [`SyncCommitCreated`](crate::package::event::PackageEvent::SyncCommitCreated)
    /// for each commit, then a completion event with the push result.
    fn execute_push(
        &self,
        commits: Vec<ConfirmedCommit>,
    ) -> impl Future<Output = EventStream> + Send;

    /// Fetch and fast-forward merge from the remote.
    ///
    /// Refuses if there are staged changes (indicating an in-progress commit).
    /// Modified and untracked files are allowed — `git merge --ff-only` handles
    /// them safely (fails if they'd conflict). Emits progress events during
    /// fetch and merge, then a completion event with what changed.
    fn pull(&self) -> impl Future<Output = EventStream> + Send;
}
