//! SyncService port (trait) for git sync operations.
//!
//! Defines the hexagonal architecture port for syncing selfie package specs
//! and dotfiles via git. The [`SyncService`] trait abstracts the sync workflow,
//! allowing different implementations and enabling testing through mocking.
//!
//! Push uses a two-phase architecture:
//! - [`SyncService::prepare_push`] — query step that generates commit proposals
//! - [`SyncService::execute_push`] — mutation step that stages, commits, and pushes

use std::future::Future;
use std::path::PathBuf;

use thiserror::Error;

use crate::package::event::EventStream;

/// Errors from sync preparation operations.
#[derive(Debug, Error)]
pub enum SyncError {
    /// The package directory is not inside a git repository.
    #[error("not a git repository: {path}")]
    NotARepo { path: PathBuf },

    /// A git operation failed during preparation.
    #[error("{0}")]
    GitError(String),
}

/// Options controlling how `sync push` behaves.
#[derive(Debug, Clone, Default)]
pub struct PushOptions {
    /// Create a single commit for all changes instead of per-package commits.
    pub batch: bool,
    /// Override the commit message (only meaningful with `batch = true`).
    pub message: Option<String>,
    /// Skip per-commit prompts — use generated messages as-is.
    pub auto_accept: bool,
    /// Include non-package files in a "housekeeping" commit.
    pub include_ungrouped: bool,
}

/// A proposed commit generated by [`SyncService::prepare_push`].
///
/// Each pending commit groups related files (typically belonging to one package)
/// with a generated conventional commit message. The caller can inspect, edit,
/// or skip individual commits before passing them to [`SyncService::execute_push`].
#[derive(Debug, Clone)]
pub struct PendingCommit {
    /// Package name, or `"housekeeping"` for ungrouped files.
    pub name: String,
    /// Generated conventional commit message.
    pub message: String,
    /// Files to stage for this commit (relative to repo root).
    pub files: Vec<PathBuf>,
}

/// Result of [`SyncService::prepare_push`].
///
/// Contains proposed commits for new changes, plus metadata about the
/// current branch state (e.g., how many commits are already ahead of the
/// remote). This allows callers to distinguish "nothing at all" from
/// "no new commits but existing commits need pushing."
#[derive(Debug, Clone)]
pub struct PrepareResult {
    /// Proposed commits for uncommitted changes.
    pub pending_commits: Vec<PendingCommit>,
    /// Number of local commits already ahead of the remote.
    /// When this is > 0 and `pending_commits` is empty, the caller should
    /// still call [`SyncService::execute_push`] to push existing commits.
    pub ahead: usize,
    /// Non-fatal warnings the caller should display (e.g., ungrouped files skipped).
    pub warnings: Vec<String>,
}

/// A commit confirmed by the caller, with a potentially edited message.
///
/// Created from a [`PendingCommit`] after the caller has had a chance to
/// review and optionally edit the message.
#[derive(Debug, Clone)]
pub struct ConfirmedCommit {
    /// Files to stage for this commit (relative to repo root).
    pub files: Vec<PathBuf>,
    /// Final commit message (may have been edited by the user).
    pub message: String,
}

/// Port for git sync operations (Hexagonal Architecture).
///
/// This trait abstracts the sync workflow — status, push, and pull — so that
/// the CLI and MCP server can consume it without knowing about git internals.
///
/// # Two-Phase Push
///
/// Push is split into a preparation phase ([`prepare_push`](Self::prepare_push))
/// that returns proposed commits, and an execution phase
/// ([`execute_push`](Self::execute_push)) that performs the actual git operations.
/// This allows callers to prompt users for confirmation between phases.
#[cfg_attr(any(test, feature = "with_mocks"), mockall::automock)]
pub trait SyncService: Send + Sync {
    /// Get combined repo status and dotfile drift summary.
    ///
    /// Emits [`SyncRepoStatus`](crate::package::event::PackageEvent::SyncRepoStatus)
    /// and [`SyncDriftSummary`](crate::package::event::PackageEvent::SyncDriftSummary)
    /// events, then completes.
    fn status(&self) -> impl Future<Output = EventStream> + Send;

    /// Analyze uncommitted changes and generate per-package commit proposals.
    ///
    /// This is a **non-mutating query** — no git state is changed. Returns a
    /// [`PrepareResult`] containing proposed commits and branch state metadata.
    ///
    /// Errors are returned directly (not as events) because this is a preparation
    /// step, not a long-running operation.
    fn prepare_push(
        &self,
        options: &PushOptions,
    ) -> impl Future<Output = Result<PrepareResult, SyncError>> + Send;

    /// Stage, commit, and push the confirmed commits.
    ///
    /// Emits [`SyncCommitCreated`](crate::package::event::PackageEvent::SyncCommitCreated)
    /// for each commit, then a completion event with the push result.
    fn execute_push(
        &self,
        commits: Vec<ConfirmedCommit>,
    ) -> impl Future<Output = EventStream> + Send;

    /// Fetch and fast-forward merge from the remote.
    ///
    /// Refuses if the working tree is dirty. Emits progress events during
    /// fetch and merge, then a completion event with what changed.
    fn pull(&self) -> impl Future<Output = EventStream> + Send;
}
